### ISSUE TITLE
HOSVD

### ISSUE THREAD

**Issue by mertall** [amancern3/opencv_scripts#1]
Your code structure is sick man.

I wanted to use an alg called HOSVD and i have it coded, i just never learnt opencv. Do you wanna try your model with an algorithm i coded? The algorithm will give us an emotion vector. Lets say you walk into the main room, the camera will judge your emotion and change your lighting based on this and unlock your door for you. We can plug in usb into our door handles and figure out how to program them to unlock. maybe by opening our keys? idk 

But ya, didn't realize you had all of this done, I made my own repo just with the alg and code idea.

**Comment by amancern3** [comment]
Thank you for the compliment, I have a basic facial recognition software going right now but I would love to collaborate and make a branch on this new feature
